baseURL = "https://janetyiplaw.com"
languageCode = "en-us"
title = "Janet Law-Yip"
theme = "v1"
paginate = "100"

[params]
  author = "Jennifer Yip"

[permalinks]
  posts = "/:filename/"
  stories = "/:filename/"
