baseURL = "https://janetyiplaw.com"
languageCode = "en-us"
title = "In loving memory of Janet Law-Yip"
theme = "v1"
paginate = "100"

[params]
  author = "Jennifer Yip"
  description = "Janet Chuk Pui Law-Yip passed away peacefully on November 29th, 2006 at Kingston General Hospital with her family by her side."

[permalinks]
  posts = "/:filename/"
  stories = "/:filename/"
